import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const runtimeConfig = window.APP_CONFIG || {};

// Replace these values in `config.js` with your Supabase project settings.
const SUPABASE_URL = runtimeConfig.SUPABASE_URL || 'https://your-project.supabase.co';
const SUPABASE_ANON_KEY = runtimeConfig.SUPABASE_ANON_KEY || 'your-anon-key';
export const GOOGLE_CLIENT_ID = runtimeConfig.GOOGLE_CLIENT_ID || 'your-google-client-id.apps.googleusercontent.com';

const isConfigured =
  SUPABASE_URL !== 'https://your-project.supabase.co' &&
  SUPABASE_ANON_KEY !== 'your-anon-key';

export const supabase = isConfigured
  ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
  : null;

export const SUPABASE_READY = isConfigured;

export const getConfigMessage = () =>
  'Update `config.js` with your Supabase URL and anon key, then run the latest GCC AI Manager schema.';

export const schemaSQL = `-- If you already created the older starter tables, reset or drop them before running this upgraded schema.
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  access_level text not null default 'user' check (access_level in ('super_admin', 'admin', 'user')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists access_level text not null default 'user';

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and access_level in ('super_admin', 'admin')
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Make the very first registered account the super admin.
  insert into public.profiles (id, email, full_name, access_level)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case
      when lower(coalesce(new.email, '')) = 'mtanvir.sk90@gmail.com' then 'super_admin'
      when exists (select 1 from public.profiles) then 'user'
      else 'super_admin'
    end
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = excluded.full_name;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

update public.profiles
set access_level = 'super_admin'
where lower(coalesce(email, '')) = 'mtanvir.sk90@gmail.com';

create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  name text not null unique,
  city text not null,
  country text not null,
  address text,
  image_urls text[] not null default '{}',
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  short_name text not null,
  logo_url text,
  team_count integer not null default 1,
  squad_labels text[] not null default '{}',
  primary_color text default '#d32027',
  secondary_color text default '#3944a7',
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.venues add column if not exists address text;
alter table public.venues add column if not exists image_urls text[] not null default '{}';
alter table public.teams add column if not exists logo_url text;
alter table public.teams add column if not exists team_count integer not null default 1;
alter table public.teams add column if not exists squad_labels text[] not null default '{}';
alter table public.teams add column if not exists primary_color text default '#d32027';
alter table public.teams add column if not exists secondary_color text default '#3944a7';

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  name text not null,
  jersey_number integer not null default 0,
  role text not null,
  batsman_type text,
  bowler_type text,
  batting_style text not null,
  bowling_style text not null,
  player_category text,
  profile_image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.players add column if not exists jersey_number integer not null default 0;
alter table public.players add column if not exists batsman_type text;
alter table public.players add column if not exists bowler_type text;
alter table public.players add column if not exists player_category text;
alter table public.players add column if not exists profile_image_url text;

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null,
  label text not null,
  url text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.google_sheet_connections (
  id bigint generated by default as identity primary key,
  spreadsheet_id text not null unique,
  spreadsheet_url text,
  players_range text not null default 'Players!A:G',
  status text not null default 'active' check (status in ('active', 'inactive')),
  connected_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.google_sheet_permissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  can_view boolean not null default false,
  can_import boolean not null default false,
  can_export boolean not null default false,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  team1_id bigint not null references public.teams(id) on delete cascade,
  team2_id bigint not null references public.teams(id) on delete cascade,
  venue_id bigint not null references public.venues(id) on delete restrict,
  match_date date not null,
  match_time time,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint different_teams check (team1_id <> team2_id)
);

alter table public.matches add column if not exists match_time time;

create table if not exists public.lineups (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  team_side text not null default 'home' check (team_side in ('home', 'away')),
  match_role text not null default 'player' check (match_role in ('player', 'captain', 'vice_captain', 'wicketkeeper')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint unique_match_player unique (match_id, player_id)
);

alter table public.lineups add column if not exists team_side text not null default 'home';
alter table public.lineups add column if not exists match_role text not null default 'player';
alter table public.lineups drop constraint if exists unique_match_role_per_match;
create unique index if not exists unique_match_role_per_match
  on public.lineups (match_id, team_side, match_role)
  where match_role <> 'player';

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  match_id bigint not null unique references public.matches(id) on delete cascade,
  team1_score integer not null,
  team2_score integer not null,
  winner_team_id bigint references public.teams(id) on delete set null,
  toss_winner_name text,
  toss_decision text,
  summary text,
  team1_innings_summary text,
  team2_innings_summary text,
  player_of_match text,
  player_of_match_style text,
  best_score text,
  best_scorer_name text,
  best_scorer_style text,
  best_bowler_name text,
  best_bowler_figures text,
  best_bowler_style text,
  player_image_url text,
  best_scorer_image_url text,
  best_bowler_image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.results add column if not exists player_of_match text;
alter table public.results add column if not exists player_of_match_style text;
alter table public.results add column if not exists toss_winner_name text;
alter table public.results add column if not exists toss_decision text;
alter table public.results add column if not exists best_score text;
alter table public.results add column if not exists team1_innings_summary text;
alter table public.results add column if not exists team2_innings_summary text;
alter table public.results add column if not exists best_scorer_name text;
alter table public.results add column if not exists best_scorer_style text;
alter table public.results add column if not exists best_bowler_name text;
alter table public.results add column if not exists best_bowler_figures text;
alter table public.results add column if not exists best_bowler_style text;
alter table public.results add column if not exists player_image_url text;
alter table public.results add column if not exists best_scorer_image_url text;
alter table public.results add column if not exists best_bowler_image_url text;

alter table public.profiles enable row level security;
alter table public.venues enable row level security;
alter table public.teams enable row level security;
alter table public.players enable row level security;
alter table public.social_links enable row level security;
alter table public.google_sheet_connections enable row level security;
alter table public.google_sheet_permissions enable row level security;
alter table public.matches enable row level security;
alter table public.lineups enable row level security;
alter table public.results enable row level security;

drop policy if exists "profiles self read" on public.profiles;
drop policy if exists "profiles self insert" on public.profiles;
drop policy if exists "profiles bootstrap self promote" on public.profiles;
drop policy if exists "profiles admin all" on public.profiles;
drop policy if exists "venues authenticated access" on public.venues;
drop policy if exists "teams authenticated access" on public.teams;
drop policy if exists "players authenticated access" on public.players;
drop policy if exists "social links authenticated access" on public.social_links;
drop policy if exists "sheet connections read access" on public.google_sheet_connections;
drop policy if exists "sheet connections admin all" on public.google_sheet_connections;
drop policy if exists "sheet permissions self read" on public.google_sheet_permissions;
drop policy if exists "sheet permissions admin all" on public.google_sheet_permissions;
drop policy if exists "matches authenticated access" on public.matches;
drop policy if exists "lineups authenticated access" on public.lineups;
drop policy if exists "results authenticated access" on public.results;

create policy "profiles self read"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "profiles self insert"
  on public.profiles
  for insert
  with check (auth.uid() = id);

create policy "profiles bootstrap self promote"
  on public.profiles
  for update
  using (auth.uid() = id and lower(coalesce(email, '')) = 'mtanvir.sk90@gmail.com')
  with check (auth.uid() = id and lower(coalesce(email, '')) = 'mtanvir.sk90@gmail.com' and access_level = 'super_admin');

create policy "profiles admin all"
  on public.profiles
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "venues authenticated access"
  on public.venues
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "teams authenticated access"
  on public.teams
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "players authenticated access"
  on public.players
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "social links authenticated access"
  on public.social_links
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "sheet connections read access"
  on public.google_sheet_connections
  for select
  using (auth.role() = 'authenticated');

create policy "sheet connections admin all"
  on public.google_sheet_connections
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "sheet permissions self read"
  on public.google_sheet_permissions
  for select
  using (auth.uid() = user_id or public.is_admin());

create policy "sheet permissions admin all"
  on public.google_sheet_permissions
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "matches authenticated access"
  on public.matches
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "lineups authenticated access"
  on public.lineups
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "results authenticated access"
  on public.results
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

insert into storage.buckets (id, name, public)
values
  ('club-assets', 'club-assets', true),
  ('player-assets', 'player-assets', true),
  ('venue-assets', 'venue-assets', true)
on conflict (id) do nothing;

drop policy if exists "public can view club assets" on storage.objects;
drop policy if exists "public can view player assets" on storage.objects;
drop policy if exists "public can view venue assets" on storage.objects;
drop policy if exists "authenticated can upload club assets" on storage.objects;
drop policy if exists "authenticated can upload player assets" on storage.objects;
drop policy if exists "authenticated can upload venue assets" on storage.objects;
drop policy if exists "authenticated can update club assets" on storage.objects;
drop policy if exists "authenticated can update player assets" on storage.objects;
drop policy if exists "authenticated can update venue assets" on storage.objects;
drop policy if exists "authenticated can delete club assets" on storage.objects;
drop policy if exists "authenticated can delete player assets" on storage.objects;
drop policy if exists "authenticated can delete venue assets" on storage.objects;

create policy "public can view club assets"
  on storage.objects
  for select
  using (bucket_id = 'club-assets');

create policy "public can view player assets"
  on storage.objects
  for select
  using (bucket_id = 'player-assets');

create policy "public can view venue assets"
  on storage.objects
  for select
  using (bucket_id = 'venue-assets');

create policy "authenticated can upload club assets"
  on storage.objects
  for insert
  with check (bucket_id = 'club-assets' and auth.role() = 'authenticated');

create policy "authenticated can upload player assets"
  on storage.objects
  for insert
  with check (bucket_id = 'player-assets' and auth.role() = 'authenticated');

create policy "authenticated can upload venue assets"
  on storage.objects
  for insert
  with check (bucket_id = 'venue-assets' and auth.role() = 'authenticated');

create policy "authenticated can update club assets"
  on storage.objects
  for update
  using (bucket_id = 'club-assets' and auth.role() = 'authenticated');

create policy "authenticated can update player assets"
  on storage.objects
  for update
  using (bucket_id = 'player-assets' and auth.role() = 'authenticated');

create policy "authenticated can update venue assets"
  on storage.objects
  for update
  using (bucket_id = 'venue-assets' and auth.role() = 'authenticated');

create policy "authenticated can delete club assets"
  on storage.objects
  for delete
  using (bucket_id = 'club-assets' and auth.role() = 'authenticated');

create policy "authenticated can delete player assets"
  on storage.objects
  for delete
  using (bucket_id = 'player-assets' and auth.role() = 'authenticated');

create policy "authenticated can delete venue assets"
  on storage.objects
  for delete
  using (bucket_id = 'venue-assets' and auth.role() = 'authenticated');`;
